name: Deploy para ZABBIX

on:
  push:
    branches:
      - master  # Garante que o deploy só ocorra na branch correta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Ajustar permissões da pasta no servidor remoto
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} << 'EOF'
            chmod 777 /root/zabbix
          EOF

      - name: Copiar arquivos para o servidor remoto
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" ./ root@${{ secrets.REMOTE_HOST }}:/root/zabbix

      - name: Executar docker-compose no servidor
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd /root/zabbix || exit 1
            docker-compose up -d --build
            mv queue.php /var/lib/docker/volumes/zabbix_webhook/_data/html/
            chmod +x backup.sh
            chmod +x particionamento.sh
            chmod +x hosts.py
            chmod +x envio.sh
            
          EOF
